### ISSUE TITLE
Cant compile with Asterisk 13.1.0 on Ubuntu 16.04

### ISSUE THREAD

**Issue by voatsap** [unispeech/asterisk-unimrcp#29]
Hello, 
I have installed 
```
root@iCall-UniMRCP:~/asterisk-unimrcp# asterisk -V
Asterisk 13.1.0~dfsg-1.1ubuntu4.1
```
Here the configure output
https://gist.github.com/voatsap/db875f5d6fa8f4d45b96992d5444b1fb

Here the compilation error:
https://gist.github.com/voatsap/30e5e39ade6419260fd68ff9f6245b4b

please suggest

**Comment by achaloyan** [comment]
Check this out

https://issues.asterisk.org/jira/browse/ASTERISK-25503

**Comment by voatsap** [comment]
Same problem with the flags:

```
Asterisk version.............. : 13.1.0
UniMRCP version............... : 1.6.0
UniMRCP modules version....... : 1.5.1

Compiler...................... : gcc
Compiler flags................ : -g -O2
Preprocessor definitions...... :
Linker flags.................. : -z muldefs

Modules install path...........: /usr/lib/asterisk/modules
Configuration install path.....: /etc/asterisk
XML doc install path...........: /var/lib/asterisk/documentation/thirdparty

Speech resource module.........: yes
Application module.............: yes

/usr/include/asterisk/strings.h:1099: multiple definition of `ast_tech_to_upper'
.libs/audio_queue.o:/usr/include/asterisk/strings.h:1099: first defined here
.libs/app_unimrcp.o: In function `ast_rq_is_int':
/usr/include/asterisk/config.h:1116: multiple definition of `ast_rq_is_int'
.libs/audio_queue.o:/usr/include/asterisk/config.h:1116: first defined here
collect2: error: ld returned 1 exit status
Makefile:435: recipe for target 'app_unimrcp.la' failed
make[1]: *** [app_unimrcp.la] Error 1
make[1]: Leaving directory '/root/asterisk-unimrcp/app-unimrcp'

```

**Comment by achaloyan** [comment]
My understanding is Asterisk itself needs to be compiled with "-z muldefs".

**Comment by achaloyan** [comment]
I would guess the problem is solved.
